services:
  rallly:
    container_name: rallly
    image: lukevella/rallly:3.10.0
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    depends_on:
      - rallly-db
    ports:
      - 3060:3000
    environment:
      - DATABASE_URL=${RALLY_POSTGRES_URL}
      - SECRET_PASSWORD=${SECRET_PASSWORD}
      - NEXT_PUBLIC_BASE_URL=${RALLY_BASE_URL}
      - ALLOWED_EMAILS=*@rodneyosodo.com
      - NOREPLY_EMAIL=${SMTP_NAME}
      - SUPPORT_EMAIL=${SMTP_NAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=true
      - SMTP_USER=${SMTP_NAME}
      - SMTP_PWD=${SMTP_PASSWORD}

  rallly-db:
    container_name: rallly-db
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    volumes:
      - ~/docker-volumes/rallly/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${RALLY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${RALLY_POSTGRES_PASSWORD}
      - POSTGRES_DB=${RALLY_POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
