services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.31.0
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    volumes:
      - ~/docker-volumes/vaultwarden-data:/data
    environment:
      - SIGNUPS_ALLOWED=false
      - DOMAIN=${VAULTWARDEN_DOMAIN}
    ports:
      - 3010:80
