version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    groups:
      gh-dependency:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directories: ["docker-compose/*/"]
    schedule:
      interval: "monthly"
      day: "monday"
    groups:
      docker-dependency:
        patterns:
          - "*"
