services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: minio
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    command: server /data --console-address ":9001"
    ports:
      - 4050:9000
      - 4051:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ~/docker-volumes/minio:/data
