services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.5.0
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    ports:
      - 4080:9090
      - 8000:8000
    volumes:
      - ./docker-compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ~/docker-volumes/prometheus/data:/prometheus
