global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: cloudflared
    static_configs:
      - targets:
          - cloudflared:4090

  - job_name: dawarich-app
    static_configs:
      - targets:
          - dawarich-app:9394
          - dawarich-sidekiq:9394

  - job_name: endlessh
    static_configs:
      - targets:
          - endlessh:2112

  - job_name: opengist
    static_configs:
      - targets:
          - opengist:3021
