services:
  private-gpt:
    container_name: private-gpt
    image: ghcr.io/imartinez/privategpt:sha-3e67e21
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    volumes:
      - ~/docker-volumes/private-gpt/local_data:/home/worker/app/local_data
      - ~/docker-volumes/private-gpt/models:/home/worker/app/models
    ports:
      - 3060:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: local
