services:
  kener:
    container_name: kener
    image: rajnandan1/kener:3.2.13
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Africa/Nairobi
      - PUID=1000
      - PGID=1000
      - PORT=4040
      - KENER_SECRET_KEY=${KENER_SECRET_KEY}
      - ORIGIN=${KENER_ORIGIN}
    ports:
      - 4040:4040
    volumes:
      - ~/docker-volumes/kener/data:/app/database:rw
      - ~/docker-volumes/kener/uploads:/app/uploads:rw
