services:
  kener:
    container_name: kener
    image: rajnandan1/kener:2.0.0
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Africa/Nairobi
      - PUID=1000
      - PGID=1000
      - PORT=4040
    ports:
      - 4040:4040
    volumes:
      - ./docker-compose/kener/config:/app/config
      - ~/docker-volumes/kener/data:/app/database:rw

