services:
  opengist:
    container_name: opengist
    image: ghcr.io/thomiceli/opengist:1.13.1
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    ports:
      - 3020:6157
      - 3021:3021
      # - 2222:2222 # SSH port, can be removed if you don't use SSH
    volumes:
      - ~/docker-volumes/opengist:/opengist
    environment:
      - UID=1000
      - GID=1000
      - OG_EXTERNAL_URL=https://gist.rodneyosodo.com
      - OG_GIT_DEFAULT_BRANCH=main
      - OG_METRICS_ENABLED=true
      - OG_METRICS_HOST=0.0.0.0
      - OG_METRICS_PORT=3021
      - OG_SSH_GIT_ENABLED=false
      - OG_LOG_LEVEL=warn
