services:
  cal:
    container_name: cal
    image: calcom/cal.com:v4.3.3
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    ports:
      - 4050:3000
    environment:
      - DATABASE_URL=${CAL_DATABASE_URL}
      - DATABASE_DIRECT_URL=${CAL_DATABASE_URL}
      - NEXTAUTH_SECRET=${CAL_NEXTAUTH_SECRET}
      - CALENDSO_ENCRYPTION_KEY=${CAL_ENCRYPTION_KEY}
      - GOOGLE_API_CREDENTIALS=${CAL_GOOGLE_API_CREDENTIALS}
      - CALCOM_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_WEBAPP_URL=${CAL_WEBAPP_URL}
      - EMAIL_FROM=${MAIL_FROM_ADDRESS}
      - EMAIL_SERVER_HOST=${SMTP_HOST}
      - EMAIL_SERVER_PORT=${SMTP_PORT}
      - EMAIL_SERVER_USER=${SMTP_NAME}
      - EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - cal-db

  cal-db:
    container_name: cal-db
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    volumes:
      - ~/docker-volumes/cal/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${CAL_POSTGRES_USER}
      - POSTGRES_PASSWORD=${CAL_POSTGRES_PASSWORD}
      - POSTGRES_DB=${CAL_POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
