services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.23.15
    restart: unless-stopped
    networks:
      - homelab-network
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/docker-volumes/uptime-kuma-data:/app/data
    security_opt:
      - no-new-privileges:true
