services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    restart: unless-stopped
    networks:
      homelab-network:
        ipv4_address: 172.30.0.100
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 2050:80/tcp
    environment:
      - TZ=Africa/Nairobi
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - PIHOLE_DNS_=172.30.0.101#2051
      - DNSMASQ_LISTENING=all
      - PIHOLE_UID=1000
      - PIHOLE_GID=1000
    volumes:
      - ~/docker-volumes/pihole:/etc/pihole
      - ~/docker-volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    security_opt:
      - no-new-privileges:true
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    image: mvance/unbound:1.20.0
    restart: unless-stopped
    networks:
      homelab-network:
        ipv4_address: 172.30.0.101
    volumes:
      - ./docker-compose/pihole/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
    ports:
      - 2051:53/tcp
      - 2051:53/udp
    security_opt:
      - no-new-privileges:true
