services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2025.8.1
    restart: unless-stopped
    command: tunnel --metrics 0.0.0.0:4090 --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    networks:
      - homelab-network
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
    security_opt:
      - no-new-privileges:true
    ports:
      - 4090:4090
